version: '3'
services:
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx.docker
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        links:
            - php-fpm
    php-fpm:
        build:
            context: ./
            dockerfile: docker/php-fpm.docker
        volumes:
            - ./:/var/www
        depends_on:
            - sqlite
    php-cli:
        build:
            context: ./
            dockerfile: docker/php-cli.docker
        volumes:
            - ./:/var/www
        depends_on:
            - sqlite
        tty: true
    frontend-nodejs:
        image: node:20-bullseye
        volumes:
            - ./:/var/www/
        working_dir: /var/www/
        tty: true
        user: root
        ports:
            - 5173:5173
    sqlite:
        image: keinos/sqlite3
        volumes:
            - ./data:/db
        command: sh -c "sqlite3 /db/database.db .dump > /db/dump.sql"

